server:
  port: 8989
  servlet:
    context-path: /users

spring:
  application:
    name: users
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootvue?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456789
mybatis:
  type-aliases-package: com.baiyi.entity
  mapper-locations: classpath:com/baiyi/mapper/*.xml